document.write('<!DOCTYPE html>');
document.write('<html>');
document.write('<head>');
document.write('  <meta charset="utf-8" />');
document.write('  <link rel="icon" href="/favicon.ico" />');
document.write('  <meta name="viewport" content="width=device-width, initial-scale=1" />');
document.write('  <meta name="theme-color" content="#000000" />');
document.write('  <title>Desktop - 1</title>');
document.write('  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter%3A400"/>');
document.write('  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A400"/>');
document.write('  <link rel="stylesheet" href="./styles/desktop-1.css"/>');
document.write('</head>');
document.write('<body>');
document.write('<div class="desktop-1-Z7T">');
document.write('  <div class="desktop-1-x9b">');
document.write('    <div class="auto-group-b1u7-Fnu">');
document.write('      <div class="rectangle-1-yyo">');
document.write('      </div>');
document.write('      <p class="hotel-management-system-Uff">HOTEL MANAGEMENT SYSTEM</p>');
document.write('      <div class="rectangle-6-GrR">');
document.write('      </div>');
document.write('      <p class="function-list-13K">');
document.write('      Function ');
document.write('      <br/>');
document.write('      list');
document.write('      </p>');
document.write('      <p class="employee-info-WEy">');
document.write('      Employee');
document.write('      <br/>');
document.write('      Info');
document.write('      </p>');
document.write('      <p class="management-DQH">Management</p>');
document.write('      <p class="reserve-and-checkout-vpV">');
document.write('      Reserve ');
document.write('      <br/>');
document.write('      and');
document.write('      <br/>');
document.write('      Checkout');
document.write('      </p>');
document.write('      <p class="room-info-management-eVb">');
document.write('      Room ');
document.write('      <br/>');
document.write('      Info');
document.write('      <br/>');
document.write('      Management');
document.write('      </p>');
document.write('      <p class="customer-info-query-ZsT">');
document.write('      Customer');
document.write('      <br/>');
document.write('      Info');
document.write('      <br/>');
document.write('      Query');
document.write('      </p>');
document.write('      <p class="change-password-fvV">');
document.write('      Change');
document.write('      <br/>');
document.write('      Password');
document.write('      </p>');
document.write('      <div class="rectangle-7-Lmj">');
document.write('      </div>');
document.write('      <p class="employee-log-in-please-enter-correct-username-and-password-and-click-login-button-and-enter-to-the-system-tYM">');
document.write('      Employee Log In');
document.write('      <br/>');
document.write('      Please enter correct username  and password and click “Login” button and enter to the system');
document.write('      </p>');
document.write('    </div>');
document.write('    <div class="auto-group-lv5x-8Bo">');
document.write('      <div class="auto-group-jb6d-Rwb">');
document.write('        <p class="username--APP">');
document.write('        Username:');
document.write('        <br/>');
document.write('        ');
document.write('        </p>');
document.write('        <div class="rectangle-10-6H3">');
document.write('        </div>');
document.write('      </div>');
document.write('      <img class="rectangle-5-RKK" src="./assets/rectangle-5-zD3.png"/>');
document.write('      <div class="auto-group-p4ku-XNM">');
document.write('        <p class="password--dwB">Password:</p>');
document.write('        <div class="rectangle-9-ARK">');
document.write('        </div>');
document.write('      </div>');
document.write('      <p class="welcome-to-hotel-management-system-7LZ">Welcome to hotel management system</p>');
document.write('      <div class="auto-group-8bkj-dJu">');
document.write('        <p class="your-user-type-is-N1b">Your user type is </p>');
document.write('        <img class="line-1-gHB" src="./assets/line-1.png"/>');
document.write('      </div>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>');
document.write('</body>');
