document.write('<!DOCTYPE html>');
document.write('<html>');
document.write('<head>');
document.write('  <meta charset="utf-8" />');
document.write('  <link rel="icon" href="/favicon.ico" />');
document.write('  <meta name="viewport" content="width=device-width, initial-scale=1" />');
document.write('  <meta name="theme-color" content="#000000" />');
document.write('  <title>Desktop - 4</title>');
document.write('  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A400"/>');
document.write('  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter%3A400"/>');
document.write('  <link rel="stylesheet" href="./styles/desktop-4.css"/>');
document.write('</head>');
document.write('<body>');
document.write('<div class="desktop-4-bUq">');
document.write('  <div class="desktop-1-wYh">');
document.write('    <div class="desktop-1-uVX">');
document.write('      <div class="auto-group-h3ch-35w">');
document.write('        <div class="rectangle-1-L53">');
document.write('        </div>');
document.write('        <p class="hotel-management-system-ft1">HOTEL MANAGEMENT SYSTEM</p>');
document.write('        <div class="rectangle-6-Ywo">');
document.write('        </div>');
document.write('        <p class="function-list-HuP">');
document.write('        Function ');
document.write('        <br/>');
document.write('        list');
document.write('        </p>');
document.write('        <p class="employee-info-Bjs">');
document.write('        Employee');
document.write('        <br/>');
document.write('        Info');
document.write('        </p>');
document.write('        <p class="management-VkZ">Management</p>');
document.write('        <p class="reserve-and-checkout-1yo">');
document.write('        Reserve ');
document.write('        <br/>');
document.write('        and');
document.write('        <br/>');
document.write('        Checkout');
document.write('        </p>');
document.write('        <p class="room-info-management-HRX">');
document.write('        Room ');
document.write('        <br/>');
document.write('        Info');
document.write('        <br/>');
document.write('        Management');
document.write('        </p>');
document.write('        <p class="customer-info-query-bh7">');
document.write('        Customer');
document.write('        <br/>');
document.write('        Info');
document.write('        <br/>');
document.write('        Query');
document.write('        </p>');
document.write('        <p class="change-password-JLd">');
document.write('        Change');
document.write('        <br/>');
document.write('        Password');
document.write('        </p>');
document.write('      </div>');
document.write('      <p class="layout-1Vw">Layout</p>');
document.write('      <div class="auto-group-7zp5-M41">');
document.write('        <div class="auto-group-tv4h-U8d">Reservation</div>');
document.write('        <div class="auto-group-iobb-8iy">');
document.write('          <div class="auto-group-cjh3-Sjf">');
document.write('            <img class="rectangle-5-PQ1" src="./assets/rectangle-5.png"/>');
document.write('            <div class="rectangle-8-K2m">');
document.write('            </div>');
document.write('            <p class="room-number-customer-name-phone-number-e-mail-current-time-note--Tem">');
document.write('            Room Number:');
document.write('            <br/>');
document.write('            Customer Name:');
document.write('            <br/>');
document.write('            Phone Number:');
document.write('            <br/>');
document.write('            E-mail:');
document.write('            <br/>');
document.write('            Current Time:');
document.write('            <br/>');
document.write('            Note:');
document.write('            </p>');
document.write('          </div>');
document.write('        </div>');
document.write('        <div class="auto-group-kzvz-LiZ">');
document.write('          <div class="auto-group-y8ms-4Pf">');
document.write('            <p class="return-QCd">Return</p>');
document.write('            <img class="line-14-ecm" src="./assets/line-14.png"/>');
document.write('          </div>');
document.write('          <div class="auto-group-g6to-6zZ">Reserve</div>');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>');
document.write('</body>');
