document.write('<!DOCTYPE html>');
document.write('<html>');
document.write('<head>');
document.write('  <meta charset="utf-8" />');
document.write('  <link rel="icon" href="/favicon.ico" />');
document.write('  <meta name="viewport" content="width=device-width, initial-scale=1" />');
document.write('  <meta name="theme-color" content="#000000" />');
document.write('  <title>Desktop - 3</title>');
document.write('  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter%3A400"/>');
document.write('  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A400"/>');
document.write('  <link rel="stylesheet" href="./styles/desktop-3.css"/>');
document.write('</head>');
document.write('<body>');
document.write('<div class="desktop-3-rPf">');
document.write('  <div class="desktop-1-o41">');
document.write('    <div class="desktop-1-kzq">');
document.write('      <div class="auto-group-whdp-hv5">');
document.write('        <div class="rectangle-1-Rr5">');
document.write('        </div>');
document.write('        <p class="hotel-management-system-91P">HOTEL MANAGEMENT SYSTEM</p>');
document.write('        <div class="rectangle-6-QCD">');
document.write('        </div>');
document.write('        <p class="function-list-YJR">');
document.write('        Function ');
document.write('        <br/>');
document.write('        list');
document.write('        </p>');
document.write('        <p class="employee-info-S8u">');
document.write('        Employee');
document.write('        <br/>');
document.write('        Info');
document.write('        </p>');
document.write('        <p class="management-kfP">Management</p>');
document.write('        <p class="reserve-and-checkout-sk1">');
document.write('        Reserve ');
document.write('        <br/>');
document.write('        and');
document.write('        <br/>');
document.write('        Checkout');
document.write('        </p>');
document.write('        <p class="room-info-management-z3w">');
document.write('        Room ');
document.write('        <br/>');
document.write('        Info');
document.write('        <br/>');
document.write('        Management');
document.write('        </p>');
document.write('        <p class="customer-info-query-r69">');
document.write('        Customer');
document.write('        <br/>');
document.write('        Info');
document.write('        <br/>');
document.write('        Query');
document.write('        </p>');
document.write('        <p class="change-password-9qw">');
document.write('        Change');
document.write('        <br/>');
document.write('        Password');
document.write('        </p>');
document.write('      </div>');
document.write('      <p class="layout-U7X">Layout</p>');
document.write('      <div class="auto-group-aqyz-QWy">');
document.write('        <div class="auto-group-f5tq-jJM">');
document.write('          <img class="rectangle-5-FGh" src="./assets/rectangle-5-mLy.png"/>');
document.write('          <div class="rectangle-7-n1j">');
document.write('          </div>');
document.write('          <p class="make-reservation-checkout-ykR">Make Reservation /Checkout</p>');
document.write('          <p class="room-number--5Hf">Room Number:</p>');
document.write('          <div class="rectangle-8-BrV">');
document.write('          </div>');
document.write('          <div class="rectangle-10-8Wq">');
document.write('          </div>');
document.write('          <p class="search-Gd3">search</p>');
document.write('        </div>');
document.write('        <div class="auto-group-i9do-AiR">');
document.write('          <p class="room-type--Sfw">Room Type:</p>');
document.write('          <div class="rectangle-9-kRj">');
document.write('          </div>');
document.write('          <div class="auto-group-l2xv-UsX">');
document.write('            <div class="rectangle-11-dEd">');
document.write('            </div>');
document.write('            <p class="search-Zty">search</p>');
document.write('          </div>');
document.write('        </div>');
document.write('        <div class="auto-group-38eq-FWu">');
document.write('          <div class="rectangle-12-yho">');
document.write('          </div>');
document.write('          <p class="price-hdo">Price</p>');
document.write('          <img class="line-1-NV3" src="./assets/line-1-RiD.png"/>');
document.write('          <img class="line-2-VZf" src="REPLACE_IMAGE:7:32"/>');
document.write('          <img class="line-3-RiD" src="./assets/line-3.png"/>');
document.write('          <img class="line-4-jiu" src="./assets/line-4-WrH.png"/>');
document.write('          <img class="line-5-qX3" src="./assets/line-5-ogH.png"/>');
document.write('          <img class="line-6-wpy" src="./assets/line-6-Brm.png"/>');
document.write('          <p class="room-no-V5o">');
document.write('          Room');
document.write('          <br/>');
document.write('          No');
document.write('          </p>');
document.write('          <p class="service-mp1">Service</p>');
document.write('          <p class="room-type-rKf">');
document.write('          Room');
document.write('          <br/>');
document.write('          Type');
document.write('          </p>');
document.write('          <p class="bed-size-YiH">');
document.write('          Bed ');
document.write('          <br/>');
document.write('          Size');
document.write('          </p>');
document.write('          <p class="area-sEm">Area</p>');
document.write('          <p class="reserve-checkout-aus">');
document.write('          reserve');
document.write('          <br/>');
document.write('          checkout');
document.write('          <br/>');
document.write('          ');
document.write('          </p>');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>');
document.write('</body>');
