document.write('<!DOCTYPE html>');
document.write('<html>');
document.write('<head>');
document.write('  <meta charset="utf-8" />');
document.write('  <link rel="icon" href="/favicon.ico" />');
document.write('  <meta name="viewport" content="width=device-width, initial-scale=1" />');
document.write('  <meta name="theme-color" content="#000000" />');
document.write('  <title>Desktop - 2</title>');
document.write('  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter%3A400"/>');
document.write('  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A400"/>');
document.write('  <link rel="stylesheet" href="./styles/desktop-2.css"/>');
document.write('</head>');
document.write('<body>');
document.write('<div class="desktop-2-iMb">');
document.write('  <div class="desktop-1-G8D">');
document.write('    <div class="auto-group-y4bo-cSy">');
document.write('      <div class="rectangle-1-Z7K">');
document.write('      </div>');
document.write('      <p class="hotel-management-system-Jah">HOTEL MANAGEMENT SYSTEM</p>');
document.write('      <div class="rectangle-6-CRB">');
document.write('      </div>');
document.write('      <p class="function-list-YE9">');
document.write('      Function ');
document.write('      <br/>');
document.write('      list');
document.write('      </p>');
document.write('      <p class="employee-info-EMs">');
document.write('      Employee');
document.write('      <br/>');
document.write('      Info');
document.write('      </p>');
document.write('      <p class="management-i29">Management</p>');
document.write('      <p class="reserve-and-checkout-d97">');
document.write('      Reserve ');
document.write('      <br/>');
document.write('      and');
document.write('      <br/>');
document.write('      Checkout');
document.write('      </p>');
document.write('      <p class="room-info-management-YG5">');
document.write('      Room ');
document.write('      <br/>');
document.write('      Info');
document.write('      <br/>');
document.write('      Management');
document.write('      </p>');
document.write('      <p class="customer-info-query-FRP">');
document.write('      Customer');
document.write('      <br/>');
document.write('      Info');
document.write('      <br/>');
document.write('      Query');
document.write('      </p>');
document.write('      <p class="change-password-xqb">');
document.write('      Change');
document.write('      <br/>');
document.write('      Password');
document.write('      </p>');
document.write('    </div>');
document.write('    <div class="auto-group-5jrq-eTX">');
document.write('      <div class="auto-group-hbpq-8tV">Layout</div>');
document.write('      <div class="auto-group-dsbs-yeD">Room Management System</div>');
document.write('      <div class="auto-group-az4h-DHf">');
document.write('        <p class="room-number--KLh">Room Number:</p>');
document.write('        <div class="rectangle-8-EiZ">');
document.write('        </div>');
document.write('        <div class="auto-group-tdqf-itd">search</div>');
document.write('      </div>');
document.write('      <div class="auto-group-ytjv-vzh">');
document.write('        <img class="rectangle-5-RRf" src="./assets/rectangle-5-KMF.png"/>');
document.write('        <p class="room-type--9cZ">Room Type:</p>');
document.write('        <div class="rectangle-9-3C9">');
document.write('        </div>');
document.write('        <div class="rectangle-11-x4D">');
document.write('        </div>');
document.write('        <p class="v-rfP">v</p>');
document.write('        <p class="search-XmX">search</p>');
document.write('        <div class="rectangle-12-ER3">');
document.write('        </div>');
document.write('        <p class="delete-jsb">Delete</p>');
document.write('        <p class="room-type-THo">');
document.write('        Room');
document.write('        <br/>');
document.write('        Type');
document.write('        </p>');
document.write('        <img class="line-1-mZP" src="./assets/line-1-Xiu.png"/>');
document.write('        <img class="line-2-WG5" src="./assets/line-2.png"/>');
document.write('        <img class="line-3-qp9" src="REPLACE_IMAGE:6:37"/>');
document.write('        <img class="line-4-njP" src="./assets/line-4.png"/>');
document.write('        <img class="line-5-8YM" src="./assets/line-5.png"/>');
document.write('        <img class="line-6-eFo" src="./assets/line-6.png"/>');
document.write('        <img class="line-7-yJ5" src="./assets/line-7.png"/>');
document.write('        <img class="line-8-JbF" src="./assets/line-8.png"/>');
document.write('        <p class="room-number-TDF">');
document.write('        Room');
document.write('        <br/>');
document.write('        Number');
document.write('        </p>');
document.write('        <p class="room-price-yBb">');
document.write('        Room');
document.write('        <br/>');
document.write('        Price');
document.write('        </p>');
document.write('        <p class="room-details-6GD">');
document.write('        Room');
document.write('        <br/>');
document.write('        Details');
document.write('        </p>');
document.write('        <p class="modify-neq">Modify</p>');
document.write('        <p class="delete-hmo">Delete</p>');
document.write('        <p class="detail-QRK">Detail</p>');
document.write('        <p class="detail-gtd">Detail</p>');
document.write('        <p class="delete-cGV">Delete</p>');
document.write('        <img class="line-9-8Vj" src="./assets/line-9.png"/>');
document.write('        <img class="line-10-fEm" src="./assets/line-10.png"/>');
document.write('        <img class="line-11-13j" src="./assets/line-11.png"/>');
document.write('        <div class="line-12-k1K">');
document.write('        </div>');
document.write('        <p class="room-page-Ui1">Room Page</p>');
document.write('        <div class="line-13-nyb">');
document.write('        </div>');
document.write('        <img class="vector-1-tmj" src="./assets/vector-1.png"/>');
document.write('        <img class="vector-2-QVB" src="./assets/vector-2.png"/>');
document.write('        <img class="vector-3-8g5" src="./assets/vector-3.png"/>');
document.write('        <img class="vector-4-GnH" src="./assets/vector-4.png"/>');
document.write('        <img class="vector-5-Pc1" src="./assets/vector-5.png"/>');
document.write('        <img class="vector-6-vM3" src="./assets/vector-6.png"/>');
document.write('        <img class="vector-7-F8R" src="./assets/vector-7.png"/>');
document.write('      </div>');
document.write('      <div class="auto-group-ezlm-aAh">Add Room</div>');
document.write('    </div>');
document.write('  </div>');
document.write('</div>');
document.write('</body>');
